name: Build PKG Executables

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: node18-linux-x64
            output: cottage-tandoori-helper-linux
          - os: macos-latest
            target: node18-macos-x64
            output: cottage-tandoori-helper-mac
          - os: windows-latest
            target: node18-win-x64
            output: cottage-tandoori-helper-windows.exe

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build PKG executable
        run: npx pkg . --target ${{ matrix.target }} --output ${{ matrix.output }} --compress Brotli

      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.output }}
          path: ${{ matrix.output }}

  # Create release manually when needed - artifacts are always available
  success:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Build Success
        run: |
          echo "✅ All PKG executables built successfully!"
          echo "📦 Download artifacts from this build"
          echo "🚀 Ready for restaurant deployment"
